
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `cSEM`=list(
        `type`="manual", 
        `author`="Rademaker, Manuel E. and Schuberth, Florian", 
        `year`=2020, 
        `title`="cSEM: Composite-Based Structural Equation Modeling", 
        `publisher`="R package", 
        `url`="https://floschuberth.github.io/cSEM/"), 
    `henselerSchuberth2021`=list(
        `type`="book", 
        `author`="Henseler, J\u00F6rg and Schuberth, Florian", 
        `year`=2021, 
        `title`="Composite-Based Structural Equation Modeling: Analyzing Latent and Emergent Variables", 
        `publisher`="The Guilford Press"), 
    `schuberthHenselerDijkstra2018`=list(
        `type`="article", 
        `author`="Schuberth, Florian and Henseler, J\u00F6rg and Dijkstra, Theo K.", 
        `year`=2018, 
        `title`="Confirmatory composite analysis", 
        `publisher`="Frontiers in Psychology", 
        `volume`=9, 
        `pages`=2541, 
        `doi`="10.3389/fpsyg.2018.02541"), 
    `dijkstraHenseler2015`=list(
        `type`="article",
        `author`="Dijkstra, Theo K. and Henseler, J\u00F6rg",
        `year`=2015,
        `title`="Consistent partial least squares path modeling",
        `publisher`="MIS Quarterly",
        `volume`=39,
        `number`=2,
        `pages`="297-316"),
    `CompositeSEM`=list(
        `type`="software",
        `author`="Alarfaj, Abdullah and Alamer, Abdullah A.",
        `year`=2026,
        `title`="Composite-SEM",
        `publisher`="[Jamovi module]",
        `url`="https://github.com/AbdullahAlarfaj101/Composite-SEM"))
