
# This file is automatically generated, you probably don't want to edit this

CompositeSEMOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CompositeSEMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dataCleaningEnabled = TRUE,
            cleaningMethod = "listwise",
            latent = list(
                list(label="Latent1", vars=list())),
            composite = list(
                list(label="Composite1", vars=list())),
            multg = NULL,
            mgaHenseler = TRUE,
            mgaSarstedt = FALSE,
            mgaChin = FALSE,
            mgaKeil = FALSE,
            mgaNitzl = FALSE,
            alt = "PLS",
            useBootstrap = FALSE,
            bootR = 500,
            bootCI = "CI_percentile",
            LinearBench = FALSE,
            predictFolds = 10,
            endogenousClass = list(),
            exogenousClass = list(),
            endogenousTerms = list(
                list()),
            exactFit = FALSE,
            showCompositeLoadings = FALSE,
            disattenuate = FALSE,
            robustEst = FALSE,
            modes = list(),
            showPlot = FALSE,
            abbreviate = TRUE,
            abbrevLength = 4,
            plotLayout = "tree",
            plotRotation = "2",
            showEstimates = TRUE,
            showResiduals = FALSE,
            plotFontSize = "medium",
            showSigStars = TRUE, ...) {

            super$initialize(
                package="CompositeSEM",
                name="CompositeSEM",
                requiresData=TRUE,
                ...)

            private$..dataCleaningEnabled <- jmvcore::OptionBool$new(
                "dataCleaningEnabled",
                dataCleaningEnabled,
                default=TRUE)
            private$..cleaningMethod <- jmvcore::OptionList$new(
                "cleaningMethod",
                cleaningMethod,
                options=list(
                    "listwise",
                    "mean",
                    "regression",
                    "knn"),
                default="listwise")
            private$..latent <- jmvcore::OptionArray$new(
                "latent",
                latent,
                default=list(
                    list(label="Latent1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "latent",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous",
                                "ordinal"),
                            permitted=list(
                                "numeric",
                                "factor")))))
            private$..composite <- jmvcore::OptionArray$new(
                "composite",
                composite,
                default=list(
                    list(label="Composite1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "composite",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous",
                                "ordinal"),
                            permitted=list(
                                "numeric",
                                "factor")))))
            private$..multg <- jmvcore::OptionVariable$new(
                "multg",
                multg)
            private$..mgaHenseler <- jmvcore::OptionBool$new(
                "mgaHenseler",
                mgaHenseler,
                default=TRUE)
            private$..mgaSarstedt <- jmvcore::OptionBool$new(
                "mgaSarstedt",
                mgaSarstedt,
                default=FALSE)
            private$..mgaChin <- jmvcore::OptionBool$new(
                "mgaChin",
                mgaChin,
                default=FALSE)
            private$..mgaKeil <- jmvcore::OptionBool$new(
                "mgaKeil",
                mgaKeil,
                default=FALSE)
            private$..mgaNitzl <- jmvcore::OptionBool$new(
                "mgaNitzl",
                mgaNitzl,
                default=FALSE)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "PLS",
                    "GSCA",
                    "MAXVAR"),
                default="PLS")
            private$..useBootstrap <- jmvcore::OptionBool$new(
                "useBootstrap",
                useBootstrap,
                default=FALSE)
            private$..bootR <- jmvcore::OptionInteger$new(
                "bootR",
                bootR,
                min=50,
                max=5000,
                default=500)
            private$..bootCI <- jmvcore::OptionList$new(
                "bootCI",
                bootCI,
                options=list(
                    "CI_percentile",
                    "CI_basic",
                    "CI_bc",
                    "CI_bca"),
                default="CI_percentile")
            private$..LinearBench <- jmvcore::OptionBool$new(
                "LinearBench",
                LinearBench,
                default=FALSE)
            private$..predictFolds <- jmvcore::OptionInteger$new(
                "predictFolds",
                predictFolds,
                min=2,
                max=100,
                default=10)
            private$..endogenousClass <- jmvcore::OptionTerms$new(
                "endogenousClass",
                endogenousClass,
                default=list())
            private$..exogenousClass <- jmvcore::OptionTerms$new(
                "exogenousClass",
                exogenousClass,
                default=list())
            private$..endogenousTerms <- jmvcore::OptionArray$new(
                "endogenousTerms",
                endogenousTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "endogenousTerms",
                    NULL))
            private$..exactFit <- jmvcore::OptionBool$new(
                "exactFit",
                exactFit,
                default=FALSE)
            private$..showCompositeLoadings <- jmvcore::OptionBool$new(
                "showCompositeLoadings",
                showCompositeLoadings,
                default=FALSE)
            private$..disattenuate <- jmvcore::OptionBool$new(
                "disattenuate",
                disattenuate,
                default=FALSE)
            private$..robustEst <- jmvcore::OptionBool$new(
                "robustEst",
                robustEst,
                default=FALSE)
            private$..modes <- jmvcore::OptionArray$new(
                "modes",
                modes,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "modes",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "construct",
                            NULL),
                        jmvcore::OptionList$new(
                            "mode",
                            NULL,
                            options=list(
                                "modeA",
                                "modeB"),
                            default="modeA"))))
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=FALSE)
            private$..abbreviate <- jmvcore::OptionBool$new(
                "abbreviate",
                abbreviate,
                default=TRUE)
            private$..abbrevLength <- jmvcore::OptionInteger$new(
                "abbrevLength",
                abbrevLength,
                min=1,
                max=20,
                default=4)
            private$..plotLayout <- jmvcore::OptionList$new(
                "plotLayout",
                plotLayout,
                options=list(
                    "tree",
                    "spring"),
                default="tree")
            private$..plotRotation <- jmvcore::OptionList$new(
                "plotRotation",
                plotRotation,
                options=list(
                    "2",
                    "1",
                    "3",
                    "4"),
                default="2")
            private$..showEstimates <- jmvcore::OptionBool$new(
                "showEstimates",
                showEstimates,
                default=TRUE)
            private$..showResiduals <- jmvcore::OptionBool$new(
                "showResiduals",
                showResiduals,
                default=FALSE)
            private$..plotFontSize <- jmvcore::OptionList$new(
                "plotFontSize",
                plotFontSize,
                options=list(
                    "small",
                    "medium",
                    "large"),
                default="medium")
            private$..showSigStars <- jmvcore::OptionBool$new(
                "showSigStars",
                showSigStars,
                default=TRUE)

            self$.addOption(private$..dataCleaningEnabled)
            self$.addOption(private$..cleaningMethod)
            self$.addOption(private$..latent)
            self$.addOption(private$..composite)
            self$.addOption(private$..multg)
            self$.addOption(private$..mgaHenseler)
            self$.addOption(private$..mgaSarstedt)
            self$.addOption(private$..mgaChin)
            self$.addOption(private$..mgaKeil)
            self$.addOption(private$..mgaNitzl)
            self$.addOption(private$..alt)
            self$.addOption(private$..useBootstrap)
            self$.addOption(private$..bootR)
            self$.addOption(private$..bootCI)
            self$.addOption(private$..LinearBench)
            self$.addOption(private$..predictFolds)
            self$.addOption(private$..endogenousClass)
            self$.addOption(private$..exogenousClass)
            self$.addOption(private$..endogenousTerms)
            self$.addOption(private$..exactFit)
            self$.addOption(private$..showCompositeLoadings)
            self$.addOption(private$..disattenuate)
            self$.addOption(private$..robustEst)
            self$.addOption(private$..modes)
            self$.addOption(private$..showPlot)
            self$.addOption(private$..abbreviate)
            self$.addOption(private$..abbrevLength)
            self$.addOption(private$..plotLayout)
            self$.addOption(private$..plotRotation)
            self$.addOption(private$..showEstimates)
            self$.addOption(private$..showResiduals)
            self$.addOption(private$..plotFontSize)
            self$.addOption(private$..showSigStars)
        }),
    active = list(
        dataCleaningEnabled = function() private$..dataCleaningEnabled$value,
        cleaningMethod = function() private$..cleaningMethod$value,
        latent = function() private$..latent$value,
        composite = function() private$..composite$value,
        multg = function() private$..multg$value,
        mgaHenseler = function() private$..mgaHenseler$value,
        mgaSarstedt = function() private$..mgaSarstedt$value,
        mgaChin = function() private$..mgaChin$value,
        mgaKeil = function() private$..mgaKeil$value,
        mgaNitzl = function() private$..mgaNitzl$value,
        alt = function() private$..alt$value,
        useBootstrap = function() private$..useBootstrap$value,
        bootR = function() private$..bootR$value,
        bootCI = function() private$..bootCI$value,
        LinearBench = function() private$..LinearBench$value,
        predictFolds = function() private$..predictFolds$value,
        endogenousClass = function() private$..endogenousClass$value,
        exogenousClass = function() private$..exogenousClass$value,
        endogenousTerms = function() private$..endogenousTerms$value,
        exactFit = function() private$..exactFit$value,
        showCompositeLoadings = function() private$..showCompositeLoadings$value,
        disattenuate = function() private$..disattenuate$value,
        robustEst = function() private$..robustEst$value,
        modes = function() private$..modes$value,
        showPlot = function() private$..showPlot$value,
        abbreviate = function() private$..abbreviate$value,
        abbrevLength = function() private$..abbrevLength$value,
        plotLayout = function() private$..plotLayout$value,
        plotRotation = function() private$..plotRotation$value,
        showEstimates = function() private$..showEstimates$value,
        showResiduals = function() private$..showResiduals$value,
        plotFontSize = function() private$..plotFontSize$value,
        showSigStars = function() private$..showSigStars$value),
    private = list(
        ..dataCleaningEnabled = NA,
        ..cleaningMethod = NA,
        ..latent = NA,
        ..composite = NA,
        ..multg = NA,
        ..mgaHenseler = NA,
        ..mgaSarstedt = NA,
        ..mgaChin = NA,
        ..mgaKeil = NA,
        ..mgaNitzl = NA,
        ..alt = NA,
        ..useBootstrap = NA,
        ..bootR = NA,
        ..bootCI = NA,
        ..LinearBench = NA,
        ..predictFolds = NA,
        ..endogenousClass = NA,
        ..exogenousClass = NA,
        ..endogenousTerms = NA,
        ..exactFit = NA,
        ..showCompositeLoadings = NA,
        ..disattenuate = NA,
        ..robustEst = NA,
        ..modes = NA,
        ..showPlot = NA,
        ..abbreviate = NA,
        ..abbrevLength = NA,
        ..plotLayout = NA,
        ..plotRotation = NA,
        ..showEstimates = NA,
        ..showResiduals = NA,
        ..plotFontSize = NA,
        ..showSigStars = NA)
)

CompositeSEMResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CompositeSEMResults",
    inherit = jmvcore::Group,
    active = list(
        constructsTable = function() private$.items[["constructsTable"]],
        cleaningSummaryTable = function() private$.items[["cleaningSummaryTable"]],
        infoTable = function() private$.items[["infoTable"]],
        fitTable = function() private$.items[["fitTable"]],
        exactFitTable = function() private$.items[["exactFitTable"]],
        outerCompositesTable = function() private$.items[["outerCompositesTable"]],
        outerCommonFactorsTable = function() private$.items[["outerCommonFactorsTable"]],
        reliabilityTable = function() private$.items[["reliabilityTable"]],
        htmtTable = function() private$.items[["htmtTable"]],
        vifModeBTable = function() private$.items[["vifModeBTable"]],
        vcvTable = function() private$.items[["vcvTable"]],
        structuralTable = function() private$.items[["structuralTable"]],
        mediationTable = function() private$.items[["mediationTable"]],
        predictTable = function() private$.items[["predictTable"]],
        mgaDecisionTable = function() private$.items[["mgaDecisionTable"]],
        mgaOverviewTable = function() private$.items[["mgaOverviewTable"]],
        mgaTable = function() private$.items[["mgaTable"]],
        pathPlot = function() private$.items[["pathPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="CompositeSEM",
                refs=list(
                    "CompositeSEM"))
            self$add(jmvcore::Table$new(
                options=options,
                name="constructsTable",
                title="Model Structure Summary",
                columns=list(
                    list(
                        `name`="type", 
                        `title`="Construct Type", 
                        `type`="text"),
                    list(
                        `name`="construct", 
                        `title`="Construct Name", 
                        `type`="text"),
                    list(
                        `name`="indicators", 
                        `title`="Indicators", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cleaningSummaryTable",
                title="Data Cleaning Summary",
                visible="(dataCleaningEnabled)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "dataCleaningEnabled",
                    "cleaningMethod"),
                columns=list(
                    list(
                        `name`="property", 
                        `title`="Property", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="infoTable",
                title="Model Information",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="property", 
                        `title`="Property", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fitTable",
                title="Model Fit Indices",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="exactFitTable",
                title="Exact Fit Test",
                visible=FALSE,
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "exactFit",
                    "disattenuate",
                    "robustEst",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="measure", 
                        `title`="Distance measure", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="Test statistic", 
                        `type`="number"),
                    list(
                        `name`="crit", 
                        `title`="Critical value (95%)", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="outerCompositesTable",
                title="Outer Model of Composites",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst",
                    "showCompositeLoadings"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="construct", 
                        `title`="Construct", 
                        `type`="text"),
                    list(
                        `name`="indicator", 
                        `title`="Indicator", 
                        `type`="text"),
                    list(
                        `name`="relation", 
                        `title`="Relation", 
                        `type`="text", 
                        `visible`="(showCompositeLoadings)"),
                    list(
                        `name`="estimate", 
                        `title`="Std estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `visible`="(useBootstrap)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="outerCommonFactorsTable",
                title="Outer Model of Common Factors",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="construct", 
                        `title`="Construct", 
                        `type`="text"),
                    list(
                        `name`="indicator", 
                        `title`="Indicator", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Std estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `visible`="(useBootstrap)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="reliabilityTable",
                title="Construct Reliability (Common Factors)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="construct", 
                        `title`="Construct", 
                        `type`="text"),
                    list(
                        `name`="alpha", 
                        `title`="Cronbach's alpha (\u03B1)", 
                        `type`="number"),
                    list(
                        `name`="rhoC", 
                        `title`="J\u00F6reskog's rho (\u03C9)", 
                        `superTitle`="Composite Reliability", 
                        `type`="number"),
                    list(
                        `name`="rhoA", 
                        `title`="Dijkstra-Henseler's rho (\u03C1A)", 
                        `superTitle`="Composite Reliability", 
                        `type`="number"),
                    list(
                        `name`="ave", 
                        `title`="AVE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="htmtTable",
                title="Discriminant Validity (HTMT & HTMT2)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="c1", 
                        `title`="Construct 1", 
                        `type`="text"),
                    list(
                        `name`="c2", 
                        `title`="Construct 2", 
                        `type`="text"),
                    list(
                        `name`="htmt", 
                        `title`="HTMT", 
                        `type`="number"),
                    list(
                        `name`="htmt2", 
                        `title`="HTMT2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="vifModeBTable",
                title="Variance Inflation Factors (VIFs) for Mode B Weights",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="construct", 
                        `title`="Construct", 
                        `type`="text"),
                    list(
                        `name`="indicator", 
                        `title`="Indicator", 
                        `type`="text"),
                    list(
                        `name`="vif", 
                        `title`="VIF Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="vcvTable",
                title="Construct Correlations",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="c1", 
                        `title`="Construct 1", 
                        `type`="text"),
                    list(
                        `name`="c2", 
                        `title`="Construct 2", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Correlation", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="structuralTable",
                title="Inner Model (Structural Relationships)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="rhs", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="lhs", 
                        `title`="Outcome", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="<i>\u03B2</i>", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number"),
                    list(
                        `name`="r2adj", 
                        `title`="Adj. R\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mediationTable",
                title="Indirect and Total Effects",
                visible=FALSE,
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="type", 
                        `title`="Effect Type", 
                        `type`="text"),
                    list(
                        `name`="rhs", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="lhs", 
                        `title`="Outcome", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="<i>\u03B2</i>", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `visible`="(useBootstrap)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="predictTable",
                title="Model's Out-of-Sample Predictive Power",
                visible="(LinearBench)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst",
                    "predictFolds"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="indicator", 
                        `title`="Indicator", 
                        `type`="text"),
                    list(
                        `name`="maeTarget", 
                        `title`="MAE PLS", 
                        `type`="number"),
                    list(
                        `name`="maeBench", 
                        `title`="MAE LM", 
                        `type`="number"),
                    list(
                        `name`="rmseTarget", 
                        `title`="RMSE PLS", 
                        `type`="number"),
                    list(
                        `name`="rmseBench", 
                        `title`="RMSE LM", 
                        `type`="number"),
                    list(
                        `name`="q2", 
                        `title`="Q\u00B2 predict", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mgaDecisionTable",
                title="Multi-Group Analysis - Overall Decision (\u03B1 = 5%)",
                visible="(multg)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test Method", 
                        `type`="text"),
                    list(
                        `name`="decision", 
                        `title`="Decision (\u03B1 = 5%)", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mgaOverviewTable",
                title="Multi-Group Analysis - Run Overview",
                visible="(multg)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="property", 
                        `title`="Run Metadata / Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mgaTable",
                title="Multi-Group Comparison Test Results",
                visible="(multg)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst"),
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparison Pair", 
                        `type`="text"),
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test Method", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="Test Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="decision", 
                        `title`="Decision (\u03B1 = 5%)", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="pathPlot",
                title="Path Diagram",
                width=600,
                height=450,
                renderFun=".plotPathDiagram",
                visible="(showPlot)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "bootCI",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "robustEst",
                    "modes",
                    "showPlot",
                    "plotLayout",
                    "plotRotation",
                    "showEstimates",
                    "showResiduals",
                    "plotFontSize",
                    "showSigStars",
                    "abbreviate",
                    "abbrevLength",
                    "dataCleaningEnabled",
                    "cleaningMethod")))}))

CompositeSEMBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CompositeSEMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CompositeSEM",
                name = "CompositeSEM",
                version = c(1,5,0),
                options = options,
                results = CompositeSEMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' CompositeSEM
#'
#' 
#' @param data TO ADD
#' @param dataCleaningEnabled If \code{TRUE}, the indicator variables used by
#'   the defined constructs are cleaned (according to \code{cleaningMethod})
#'   before they are passed on to cSEM.
#' @param cleaningMethod The method used to handle missing values in the
#'   indicator variables when \code{dataCleaningEnabled} is \code{TRUE}.
#' @param latent A list containing named lists that define the \code{label} of
#'   the latent endogenous variable(s) and the \code{vars} that belong to that
#'   latent.
#' @param composite A list containing named lists that define the \code{label}
#'   of the composite variables and the \code{vars} that belong to that
#'   composite.
#' @param multg .
#' @param mgaHenseler .
#' @param mgaSarstedt .
#' @param mgaChin .
#' @param mgaKeil .
#' @param mgaNitzl .
#' @param alt .
#' @param useBootstrap .
#' @param bootR .
#' @param bootCI .
#' @param LinearBench .
#' @param predictFolds .
#' @param endogenousClass Constructs classified as endogenous outcomes for
#'   directional structural modeling.
#' @param exogenousClass Constructs classified as exogenous predictors for
#'   directional structural modeling.
#' @param endogenousTerms A list of structural predictor term sets, one per
#'   construct. Each entry corresponds to a latent or composite construct in
#'   order.
#' @param exactFit .
#' @param showCompositeLoadings .
#' @param disattenuate .
#' @param robustEst .
#' @param modes .
#' @param showPlot .
#' @param abbreviate .
#' @param abbrevLength .
#' @param plotLayout .
#' @param plotRotation .
#' @param showEstimates .
#' @param showResiduals .
#' @param plotFontSize .
#' @param showSigStars .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$constructsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cleaningSummaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$infoTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$exactFitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outerCompositesTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outerCommonFactorsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$reliabilityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$htmtTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$vifModeBTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$vcvTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$structuralTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mediationTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$predictTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mgaDecisionTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mgaOverviewTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mgaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pathPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$constructsTable$asDF}
#'
#' \code{as.data.frame(results$constructsTable)}
#'
#' @export
CompositeSEM <- function(
    data,
    dataCleaningEnabled = TRUE,
    cleaningMethod = "listwise",
    latent = list(
                list(label="Latent1", vars=list())),
    composite = list(
                list(label="Composite1", vars=list())),
    multg,
    mgaHenseler = TRUE,
    mgaSarstedt = FALSE,
    mgaChin = FALSE,
    mgaKeil = FALSE,
    mgaNitzl = FALSE,
    alt = "PLS",
    useBootstrap = FALSE,
    bootR = 500,
    bootCI = "CI_percentile",
    LinearBench = FALSE,
    predictFolds = 10,
    endogenousClass = list(),
    exogenousClass = list(),
    endogenousTerms = list(
                list()),
    exactFit = FALSE,
    showCompositeLoadings = FALSE,
    disattenuate = FALSE,
    robustEst = FALSE,
    modes = list(),
    showPlot = FALSE,
    abbreviate = TRUE,
    abbrevLength = 4,
    plotLayout = "tree",
    plotRotation = "2",
    showEstimates = TRUE,
    showResiduals = FALSE,
    plotFontSize = "medium",
    showSigStars = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CompositeSEM requires jmvcore to be installed (restart may be required)")

    if ( ! missing(multg)) multg <- jmvcore::resolveQuo(jmvcore::enquo(multg))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(multg), multg, NULL))

    if (inherits(endogenousClass, "formula")) endogenousClass <- jmvcore::decomposeFormula(endogenousClass)
    if (inherits(exogenousClass, "formula")) exogenousClass <- jmvcore::decomposeFormula(exogenousClass)

    options <- CompositeSEMOptions$new(
        dataCleaningEnabled = dataCleaningEnabled,
        cleaningMethod = cleaningMethod,
        latent = latent,
        composite = composite,
        multg = multg,
        mgaHenseler = mgaHenseler,
        mgaSarstedt = mgaSarstedt,
        mgaChin = mgaChin,
        mgaKeil = mgaKeil,
        mgaNitzl = mgaNitzl,
        alt = alt,
        useBootstrap = useBootstrap,
        bootR = bootR,
        bootCI = bootCI,
        LinearBench = LinearBench,
        predictFolds = predictFolds,
        endogenousClass = endogenousClass,
        exogenousClass = exogenousClass,
        endogenousTerms = endogenousTerms,
        exactFit = exactFit,
        showCompositeLoadings = showCompositeLoadings,
        disattenuate = disattenuate,
        robustEst = robustEst,
        modes = modes,
        showPlot = showPlot,
        abbreviate = abbreviate,
        abbrevLength = abbrevLength,
        plotLayout = plotLayout,
        plotRotation = plotRotation,
        showEstimates = showEstimates,
        showResiduals = showResiduals,
        plotFontSize = plotFontSize,
        showSigStars = showSigStars)

    analysis <- CompositeSEMClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

