
# This file is automatically generated, you probably don't want to edit this

CompositeSEMOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CompositeSEMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            latent = list(
                list(label="Latent1", vars=list())),
            composite = list(
                list(label="Composite1", vars=list())),
            multg = NULL,
            alt = "PLS",
            useBootstrap = FALSE,
            bootR = 500,
            LinearBench = FALSE,
            predictFolds = 10,
            endogenousClass = list(),
            exogenousClass = list(),
            endogenousTerms = list(
                list()),
            exactFit = FALSE,
            showCompositeLoadings = FALSE,
            disattenuate = FALSE, ...) {

            super$initialize(
                package="CompositeSEM",
                name="CompositeSEM",
                requiresData=TRUE,
                ...)

            private$..latent <- jmvcore::OptionArray$new(
                "latent",
                latent,
                default=list(
                    list(label="Latent1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "latent",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous",
                                "ordinal"),
                            permitted=list(
                                "numeric",
                                "factor")))))
            private$..composite <- jmvcore::OptionArray$new(
                "composite",
                composite,
                default=list(
                    list(label="Composite1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "composite",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous",
                                "ordinal"),
                            permitted=list(
                                "numeric",
                                "factor")))))
            private$..multg <- jmvcore::OptionVariable$new(
                "multg",
                multg)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "PLS",
                    "GSCA",
                    "MAXVAR"),
                default="PLS")
            private$..useBootstrap <- jmvcore::OptionBool$new(
                "useBootstrap",
                useBootstrap,
                default=FALSE)
            private$..bootR <- jmvcore::OptionInteger$new(
                "bootR",
                bootR,
                min=50,
                max=5000,
                default=500)
            private$..LinearBench <- jmvcore::OptionBool$new(
                "LinearBench",
                LinearBench,
                default=FALSE)
            private$..predictFolds <- jmvcore::OptionInteger$new(
                "predictFolds",
                predictFolds,
                min=2,
                max=100,
                default=10)
            private$..endogenousClass <- jmvcore::OptionTerms$new(
                "endogenousClass",
                endogenousClass,
                default=list())
            private$..exogenousClass <- jmvcore::OptionTerms$new(
                "exogenousClass",
                exogenousClass,
                default=list())
            private$..endogenousTerms <- jmvcore::OptionArray$new(
                "endogenousTerms",
                endogenousTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "endogenousTerms",
                    NULL))
            private$..exactFit <- jmvcore::OptionBool$new(
                "exactFit",
                exactFit,
                default=FALSE)
            private$..showCompositeLoadings <- jmvcore::OptionBool$new(
                "showCompositeLoadings",
                showCompositeLoadings,
                default=FALSE)
            private$..disattenuate <- jmvcore::OptionBool$new(
                "disattenuate",
                disattenuate,
                default=FALSE)

            self$.addOption(private$..latent)
            self$.addOption(private$..composite)
            self$.addOption(private$..multg)
            self$.addOption(private$..alt)
            self$.addOption(private$..useBootstrap)
            self$.addOption(private$..bootR)
            self$.addOption(private$..LinearBench)
            self$.addOption(private$..predictFolds)
            self$.addOption(private$..endogenousClass)
            self$.addOption(private$..exogenousClass)
            self$.addOption(private$..endogenousTerms)
            self$.addOption(private$..exactFit)
            self$.addOption(private$..showCompositeLoadings)
            self$.addOption(private$..disattenuate)
        }),
    active = list(
        latent = function() private$..latent$value,
        composite = function() private$..composite$value,
        multg = function() private$..multg$value,
        alt = function() private$..alt$value,
        useBootstrap = function() private$..useBootstrap$value,
        bootR = function() private$..bootR$value,
        LinearBench = function() private$..LinearBench$value,
        predictFolds = function() private$..predictFolds$value,
        endogenousClass = function() private$..endogenousClass$value,
        exogenousClass = function() private$..exogenousClass$value,
        endogenousTerms = function() private$..endogenousTerms$value,
        exactFit = function() private$..exactFit$value,
        showCompositeLoadings = function() private$..showCompositeLoadings$value,
        disattenuate = function() private$..disattenuate$value),
    private = list(
        ..latent = NA,
        ..composite = NA,
        ..multg = NA,
        ..alt = NA,
        ..useBootstrap = NA,
        ..bootR = NA,
        ..LinearBench = NA,
        ..predictFolds = NA,
        ..endogenousClass = NA,
        ..exogenousClass = NA,
        ..endogenousTerms = NA,
        ..exactFit = NA,
        ..showCompositeLoadings = NA,
        ..disattenuate = NA)
)

CompositeSEMResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CompositeSEMResults",
    inherit = jmvcore::Group,
    active = list(
        constructsTable = function() private$.items[["constructsTable"]],
        infoTable = function() private$.items[["infoTable"]],
        fitTable = function() private$.items[["fitTable"]],
        exactFitTable = function() private$.items[["exactFitTable"]],
        outerCompositesTable = function() private$.items[["outerCompositesTable"]],
        outerCommonFactorsTable = function() private$.items[["outerCommonFactorsTable"]],
        reliabilityTable = function() private$.items[["reliabilityTable"]],
        htmtTable = function() private$.items[["htmtTable"]],
        vifModeBTable = function() private$.items[["vifModeBTable"]],
        vcvTable = function() private$.items[["vcvTable"]],
        structuralTable = function() private$.items[["structuralTable"]],
        mediationTable = function() private$.items[["mediationTable"]],
        predictTable = function() private$.items[["predictTable"]],
        csemOutput = function() private$.items[["csemOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="CompositeSEM")
            self$add(jmvcore::Table$new(
                options=options,
                name="constructsTable",
                title="Model Structure Summary",
                columns=list(
                    list(
                        `name`="type", 
                        `title`="Construct Type", 
                        `type`="text"),
                    list(
                        `name`="construct", 
                        `title`="Construct Name", 
                        `type`="text"),
                    list(
                        `name`="indicators", 
                        `title`="Indicators", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="infoTable",
                title="Model Information",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="property", 
                        `title`="Property", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fitTable",
                title="Model Fit Indices",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="exactFitTable",
                title="Exact Fit Test",
                visible=FALSE,
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "exactFit",
                    "disattenuate",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="measure", 
                        `title`="Distance measure", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="Test statistic", 
                        `type`="number"),
                    list(
                        `name`="crit", 
                        `title`="Critical value (95%)", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="outerCompositesTable",
                title="Outer Model of Composites",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "showCompositeLoadings"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="construct", 
                        `title`="Construct", 
                        `type`="text"),
                    list(
                        `name`="indicator", 
                        `title`="Indicator", 
                        `type`="text"),
                    list(
                        `name`="relation", 
                        `title`="Relation", 
                        `type`="text", 
                        `visible`="(showCompositeLoadings)"),
                    list(
                        `name`="estimate", 
                        `title`="Std estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `visible`="(useBootstrap)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="outerCommonFactorsTable",
                title="Outer Model of Common Factors",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="construct", 
                        `title`="Construct", 
                        `type`="text"),
                    list(
                        `name`="indicator", 
                        `title`="Indicator", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Std estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `visible`="(useBootstrap)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="reliabilityTable",
                title="Construct Reliability (Common Factors)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="construct", 
                        `title`="Construct", 
                        `type`="text"),
                    list(
                        `name`="alpha", 
                        `title`="Cronbach's alpha (\u03B1)", 
                        `type`="number"),
                    list(
                        `name`="rhoC", 
                        `title`="J\u00F6reskog's rho (\u03C9)", 
                        `superTitle`="Composite Reliability", 
                        `type`="number"),
                    list(
                        `name`="rhoA", 
                        `title`="Dijkstra-Henseler's rho (\u03C1A)", 
                        `superTitle`="Composite Reliability", 
                        `type`="number"),
                    list(
                        `name`="ave", 
                        `title`="AVE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="htmtTable",
                title="Discriminant Validity (HTMT & HTMT2)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="c1", 
                        `title`="Construct 1", 
                        `type`="text"),
                    list(
                        `name`="c2", 
                        `title`="Construct 2", 
                        `type`="text"),
                    list(
                        `name`="htmt", 
                        `title`="HTMT", 
                        `type`="number"),
                    list(
                        `name`="htmt2", 
                        `title`="HTMT2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="vifModeBTable",
                title="Variance Inflation Factors (VIFs) for Mode B Weights",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="construct", 
                        `title`="Construct", 
                        `type`="text"),
                    list(
                        `name`="indicator", 
                        `title`="Indicator", 
                        `type`="text"),
                    list(
                        `name`="vif", 
                        `title`="VIF Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="vcvTable",
                title="Construct Correlations",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="c1", 
                        `title`="Construct 1", 
                        `type`="text"),
                    list(
                        `name`="c2", 
                        `title`="Construct 2", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Correlation", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="structuralTable",
                title="Inner Model (Structural Relationships)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="rhs", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="lhs", 
                        `title`="Outcome", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="<i>\u03B2</i>", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number"),
                    list(
                        `name`="r2adj", 
                        `title`="Adj. R\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mediationTable",
                title="Indirect and Total Effects",
                visible=FALSE,
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="type", 
                        `title`="Effect Type", 
                        `type`="text"),
                    list(
                        `name`="rhs", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="lhs", 
                        `title`="Outcome", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="<i>\u03B2</i>", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% Confidence Interval", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(useBootstrap)"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `visible`="(useBootstrap)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="predictTable",
                title="Model's Out-of-Sample Predictive Power",
                visible="(LinearBench)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "LinearBench",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate",
                    "predictFolds"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text", 
                        `visible`="(multg)"),
                    list(
                        `name`="indicator", 
                        `title`="Indicator", 
                        `type`="text"),
                    list(
                        `name`="maeTarget", 
                        `title`="MAE PLS", 
                        `type`="number"),
                    list(
                        `name`="maeBench", 
                        `title`="MAE LM", 
                        `type`="number"),
                    list(
                        `name`="rmseTarget", 
                        `title`="RMSE PLS", 
                        `type`="number"),
                    list(
                        `name`="rmseBench", 
                        `title`="RMSE LM", 
                        `type`="number"),
                    list(
                        `name`="q2", 
                        `title`="Q\u00B2 predict", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="csemOutput",
                title="Multi-Group Analysis & Advanced Outputs",
                visible="(multg)",
                clearWith=list(
                    "data",
                    "latent",
                    "composite",
                    "multg",
                    "alt",
                    "useBootstrap",
                    "bootR",
                    "endogenousClass",
                    "exogenousClass",
                    "endogenousTerms",
                    "disattenuate")))}))

CompositeSEMBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "CompositeSEMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CompositeSEM",
                name = "CompositeSEM",
                version = c(1,3,0),
                options = options,
                results = CompositeSEMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' CompositeSEM
#'
#' 
#' @param data TO ADD
#' @param latent A list containing named lists that define the \code{label} of
#'   the latent endogenous variable(s) and the \code{vars} that belong to that
#'   latent.
#' @param composite A list containing named lists that define the \code{label}
#'   of the composite variables and the \code{vars} that belong to that
#'   composite.
#' @param multg .
#' @param alt .
#' @param useBootstrap .
#' @param bootR .
#' @param LinearBench .
#' @param predictFolds .
#' @param endogenousClass Constructs classified as endogenous outcomes for
#'   directional structural modeling.
#' @param exogenousClass Constructs classified as exogenous predictors for
#'   directional structural modeling.
#' @param endogenousTerms A list of structural predictor term sets, one per
#'   construct. Each entry corresponds to a latent or composite construct in
#'   order.
#' @param exactFit .
#' @param showCompositeLoadings .
#' @param disattenuate .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$constructsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$infoTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$exactFitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outerCompositesTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outerCommonFactorsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$reliabilityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$htmtTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$vifModeBTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$vcvTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$structuralTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mediationTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$predictTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$csemOutput} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$constructsTable$asDF}
#'
#' \code{as.data.frame(results$constructsTable)}
#'
#' @export
CompositeSEM <- function(
    data,
    latent = list(
                list(label="Latent1", vars=list())),
    composite = list(
                list(label="Composite1", vars=list())),
    multg,
    alt = "PLS",
    useBootstrap = FALSE,
    bootR = 500,
    LinearBench = FALSE,
    predictFolds = 10,
    endogenousClass = list(),
    exogenousClass = list(),
    endogenousTerms = list(
                list()),
    exactFit = FALSE,
    showCompositeLoadings = FALSE,
    disattenuate = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("CompositeSEM requires jmvcore to be installed (restart may be required)")

    if ( ! missing(multg)) multg <- jmvcore::resolveQuo(jmvcore::enquo(multg))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(multg), multg, NULL))

    if (inherits(endogenousClass, "formula")) endogenousClass <- jmvcore::decomposeFormula(endogenousClass)
    if (inherits(exogenousClass, "formula")) exogenousClass <- jmvcore::decomposeFormula(exogenousClass)

    options <- CompositeSEMOptions$new(
        latent = latent,
        composite = composite,
        multg = multg,
        alt = alt,
        useBootstrap = useBootstrap,
        bootR = bootR,
        LinearBench = LinearBench,
        predictFolds = predictFolds,
        endogenousClass = endogenousClass,
        exogenousClass = exogenousClass,
        endogenousTerms = endogenousTerms,
        exactFit = exactFit,
        showCompositeLoadings = showCompositeLoadings,
        disattenuate = disattenuate)

    analysis <- CompositeSEMClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

