
# This file is automatically generated, you probably don't want to edit this

testOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "testOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            .caller = "gui",
            code = "",
            latent = list(
                list(label="Latent1", vars=list())),
            composite = list(
                list(label="Composite1", vars=list())),
            multg = NULL,
            alt = "PLS",
            varEq = FALSE,
            bootR = 500,
            LinearBench = FALSE,
            ModelRelation = NULL,
            ModelRelation2 = NULL,
            ModelRelation3 = NULL,
            ModelRelation4 = NULL,
            ModelRelation5 = NULL, ...) {

            super$initialize(
                package="CSEMnew",
                name="test",
                requiresData=TRUE,
                ...)

            private$...caller <- jmvcore::OptionString$new(
                ".caller",
                .caller,
                default="gui",
                hidden=TRUE)
            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                default="",
                hidden=TRUE)
            private$..latent <- jmvcore::OptionArray$new(
                "latent",
                latent,
                default=list(
                    list(label="Latent1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "latent",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous",
                                "ordinal"),
                            permitted=list(
                                "numeric",
                                "factor")))))
            private$..composite <- jmvcore::OptionArray$new(
                "composite",
                composite,
                default=list(
                    list(label="Composite1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "composite",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous",
                                "ordinal"),
                            permitted=list(
                                "numeric",
                                "factor")))))
            private$..multg <- jmvcore::OptionVariable$new(
                "multg",
                multg)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "PLS",
                    "GSCA",
                    "MAXVAR"),
                default="PLS")
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=FALSE)
            private$..bootR <- jmvcore::OptionInteger$new(
                "bootR",
                bootR,
                min=50,
                max=5000,
                default=500)
            private$..LinearBench <- jmvcore::OptionBool$new(
                "LinearBench",
                LinearBench,
                default=FALSE)
            private$..ModelRelation <- jmvcore::OptionString$new(
                "ModelRelation",
                ModelRelation)
            private$..ModelRelation2 <- jmvcore::OptionString$new(
                "ModelRelation2",
                ModelRelation2)
            private$..ModelRelation3 <- jmvcore::OptionString$new(
                "ModelRelation3",
                ModelRelation3)
            private$..ModelRelation4 <- jmvcore::OptionString$new(
                "ModelRelation4",
                ModelRelation4)
            private$..ModelRelation5 <- jmvcore::OptionString$new(
                "ModelRelation5",
                ModelRelation5)

            self$.addOption(private$...caller)
            self$.addOption(private$..code)
            self$.addOption(private$..latent)
            self$.addOption(private$..composite)
            self$.addOption(private$..multg)
            self$.addOption(private$..alt)
            self$.addOption(private$..varEq)
            self$.addOption(private$..bootR)
            self$.addOption(private$..LinearBench)
            self$.addOption(private$..ModelRelation)
            self$.addOption(private$..ModelRelation2)
            self$.addOption(private$..ModelRelation3)
            self$.addOption(private$..ModelRelation4)
            self$.addOption(private$..ModelRelation5)
        }),
    active = list(
        .caller = function() private$...caller$value,
        code = function() private$..code$value,
        latent = function() private$..latent$value,
        composite = function() private$..composite$value,
        multg = function() private$..multg$value,
        alt = function() private$..alt$value,
        varEq = function() private$..varEq$value,
        bootR = function() private$..bootR$value,
        LinearBench = function() private$..LinearBench$value,
        ModelRelation = function() private$..ModelRelation$value,
        ModelRelation2 = function() private$..ModelRelation2$value,
        ModelRelation3 = function() private$..ModelRelation3$value,
        ModelRelation4 = function() private$..ModelRelation4$value,
        ModelRelation5 = function() private$..ModelRelation5$value),
    private = list(
        ...caller = NA,
        ..code = NA,
        ..latent = NA,
        ..composite = NA,
        ..multg = NA,
        ..alt = NA,
        ..varEq = NA,
        ..bootR = NA,
        ..LinearBench = NA,
        ..ModelRelation = NA,
        ..ModelRelation2 = NA,
        ..ModelRelation3 = NA,
        ..ModelRelation4 = NA,
        ..ModelRelation5 = NA)
)

testResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "testResults",
    inherit = jmvcore::Group,
    active = list(
        constructsTable = function() private$.items[["constructsTable"]],
        csemOutput = function() private$.items[["csemOutput"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="CSEM")
            self$add(jmvcore::Table$new(
                options=options,
                name="constructsTable",
                title="Model Structure Summary",
                columns=list(
                    list(
                        `name`="type", 
                        `title`="Construct Type", 
                        `type`="text"),
                    list(
                        `name`="construct", 
                        `title`="Construct Name", 
                        `type`="text"),
                    list(
                        `name`="indicators", 
                        `title`="Indicators", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="csemOutput",
                title="cSEM Analysis Results"))}))

testBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "testBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "CSEMnew",
                name = "test",
                version = c(1,0,0),
                options = options,
                results = testResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' CSEMnew
#'
#' 
#' @param data TO ADD
#' @param .caller .
#' @param code The lavaan syntax
#' @param latent A list containing named lists that define the \code{label} of
#'   the latent endogenous variable(s) and the \code{vars} that belong to that
#'   latent.
#' @param composite A list containing named lists that define the \code{label}
#'   of the latent exogenous variables and the \code{vars} that belong to that
#'   latent.
#' @param multg .
#' @param alt .
#' @param varEq .
#' @param bootR .
#' @param LinearBench .
#' @param ModelRelation .
#' @param ModelRelation2 .
#' @param ModelRelation3 .
#' @param ModelRelation4 .
#' @param ModelRelation5 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$constructsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$csemOutput} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$constructsTable$asDF}
#'
#' \code{as.data.frame(results$constructsTable)}
#'
#' @export
test <- function(
    data,
    .caller = "gui",
    code = "",
    latent = list(
                list(label="Latent1", vars=list())),
    composite = list(
                list(label="Composite1", vars=list())),
    multg,
    alt = "PLS",
    varEq = FALSE,
    bootR = 500,
    LinearBench = FALSE,
    ModelRelation,
    ModelRelation2,
    ModelRelation3,
    ModelRelation4,
    ModelRelation5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("test requires jmvcore to be installed (restart may be required)")

    if ( ! missing(multg)) multg <- jmvcore::resolveQuo(jmvcore::enquo(multg))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(multg), multg, NULL))


    options <- testOptions$new(
        .caller = .caller,
        code = code,
        latent = latent,
        composite = composite,
        multg = multg,
        alt = alt,
        varEq = varEq,
        bootR = bootR,
        LinearBench = LinearBench,
        ModelRelation = ModelRelation,
        ModelRelation2 = ModelRelation2,
        ModelRelation3 = ModelRelation3,
        ModelRelation4 = ModelRelation4,
        ModelRelation5 = ModelRelation5)

    analysis <- testClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

